# Generated by Django 5.2.5 on 2025-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_add_character_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_md', models.TextField(verbose_name='Content (Markdown)')),
                ('content_html', models.TextField(editable=False)),
                ('content_text', models.TextField(editable=False)),
                ('character_count', models.IntegerField(default=0, help_text='Number of non-HTML characters in content')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('page_type', models.CharField(choices=[('homepage', 'Homepage'), ('about', 'About'), ('contact', 'Contact'), ('custom', 'Custom Page')], default='custom', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages_page',
                'ordering': ['page_type', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('page_type', 'homepage')), fields=('page_type',), name='unique_homepage')],
            },
        ),
    ]
