# Generated by Django 5.2.5 on 2025-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_page_model'),
        ('tags', '0001_initial'),  # Ensure tags app has registered the model
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update the ManyToMany fields to reference tags.Tag instead of posts.Tag
                migrations.AlterField(
                    model_name='post',
                    name='tags',
                    field=models.ManyToManyField(blank=True, related_name='posts', to='tags.tag'),
                ),
                migrations.AlterField(
                    model_name='post',
                    name='derived_tags',
                    field=models.ManyToManyField(blank=True, editable=False, related_name='derived_posts', to='tags.tag'),
                ),
                # Then remove the Tag model from posts app state
                migrations.DeleteModel(
                    name='Tag',
                ),
            ],
            # Don't delete the table from database - it's used by tags app
            database_operations=[],
        ),
    ]