# Generated by Django 5.2.5 on 2025-08-17 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    app_label = 'posts'

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True, max_length=200)),
            ],
            options={
                'db_table': 'tags_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content_md', models.TextField(verbose_name='Content (Markdown)')),
                ('content_html', models.TextField(editable=False)),
                ('content_text', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('meta_description', models.TextField(blank=True)),
                ('original_page_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('aliases', models.TextField(blank=True, editable=False, help_text='Old URLs for redirects, one per line')),
                ('front_matter', models.TextField(blank=True, editable=False, help_text='Original frontmatter JSON for debugging', null=True)),
                ('derived_tags', models.ManyToManyField(blank=True, editable=False, related_name='derived_posts', to='posts.tag')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
