# Generated by Django 5.2.5 on 2025-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    app_label = 'posts'

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this post (not displayed publicly)'),
        ),
    ]
