# Generated by Django 5.2.5 on 2025-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    app_label = 'posts'

    dependencies = [
        ('posts', '0002_post_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_tiki',
            field=models.TextField(blank=True, editable=False, help_text='Original Tiki wiki markup for reference', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
