# Generated by Django 5.2.5 on 2025-09-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    app_label = 'posts'

    dependencies = [
        ('posts', '0003_add_original_tiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='redacted_count',
            field=models.IntegerField(default=0, help_text='Number of censored sections from Tiki conversion'),
        ),
    ]
