# Generated by Django 5.2.5 on 2025-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    app_label = 'posts'

    dependencies = [
        ('posts', '0004_add_redacted_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='character_count',
            field=models.IntegerField(default=0, help_text='Number of non-HTML characters in content'),
        ),
    ]
