# Generated by Django 5.2.5 on 2025-09-16 16:47

from django.db import migrations


class Migration(migrations.Migration):
    app_label = 'posts'

    dependencies = [
        ('posts', '0006_add_page_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Page',
                ),
            ],
            # Don't delete the table from database - it will be used by pages app
            database_operations=[],
        ),
    ]
