# Generated by Django 5.2.5 on 2025-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),  # Depend on posts initial since it creates the table
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Tag',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('slug', models.SlugField(unique=True, max_length=200)),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
            ],
            # No database operations - the table is created by posts migration with correct name
            database_operations=[],
        ),
    ]