"""
Django settings for vdw_server project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()


def _parse_bool_env(raw_value: str | None) -> bool:
    if raw_value is None:
        return False
    normalized = raw_value.strip().lower()
    return normalized in {'1', 'true', 'yes', 'on'}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_0ql%xgcegzyq$ejyco-*3@5u0_c-fgx*-=)4!#5z1#79-e7ej'

# SECURITY WARNING: don't run with debug turned on in production!
_debug_value = os.getenv('DJANGO_DEBUG')
if _debug_value is None:
    _debug_value = os.getenv('DEBUG')
DEBUG = _parse_bool_env(_debug_value)
del _debug_value

ALLOWED_HOSTS = ['*']  # Allow any host for now

_extra_csrf_trusted_origins = [
    origin.strip()
    for origin in os.getenv('VDW_EXTRA_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [
    'https://vitamindwiki.com',
    'https://www.vitamindwiki.com',
    'https://44.228.184.247',
    *_extra_csrf_trusted_origins,
]
del _extra_csrf_trusted_origins


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'vdw_server.apps.VdwAuthConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'pages.apps.PagesConfig',
    'site_pages.apps.SitePagesConfig',
    'search',
    'tags',
    'markdownx',
]

MIDDLEWARE = [
    'vdw_server.middleware.RequestLoggingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'vdw_server.middleware.MaintenanceModeMiddleware',
    'vdw_server.middleware.LegacyAliasRedirectMiddleware',
    'vdw_server.middleware.AdminPageRedirectMiddleware',  # Custom admin redirect
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vdw_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vdw_server.context_processors.search_preferences',
            ],
        },
    },
]

WSGI_APPLICATION = 'vdw_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Choose SQLite location based on environment
# - Local/dev: BASE_DIR/db.sqlite3
# - In Docker: BASE_DIR/data/db.sqlite3 (mounted directory)
if os.getenv('RUNNING_IN_DOCKER', '').lower() in ('1', 'true', 'yes'):
    db_path = BASE_DIR / 'data' / 'db.sqlite3'
else:
    db_path = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
SITEMAP_FILE_PATH = BASE_DIR / 'sitemap.xml'
SITE_BASE_URL = 'https://vitamindwiki.com'

# Media files - Always use S3 for storage
from .storage_settings import *

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Markdownx settings
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.fenced_code',
    'markdown.extensions.tables',
    'markdown.extensions.nl2br',
    'markdown.extensions.extra',
]

MARKDOWNX_EDITOR_RESIZABLE = True

# MeiliSearch settings
# Auto-detect environment: Docker uses service name, venv uses localhost
MEILISEARCH_URL = os.getenv('MEILISEARCH_URL', 'http://localhost:7700')
MEILISEARCH_MASTER_KEY = os.getenv('MEILISEARCH_MASTER_KEY')
MEILISEARCH_INDEX_NAME = os.getenv('MEILISEARCH_INDEX_NAME', 'pages')

# Search dropdown presentation options (extend as new modes are added)
SEARCH_RESULTS_DISPLAY_MODE = (os.getenv('SEARCH_RESULTS_DISPLAY_MODE', 'title_only') or 'title_only').strip().lower()
_valid_display_modes = {'full', 'title_only'}
if SEARCH_RESULTS_DISPLAY_MODE not in _valid_display_modes:
    raise ValueError(
        'SEARCH_RESULTS_DISPLAY_MODE must be one of %s (got %r)'
        % (sorted(_valid_display_modes), SEARCH_RESULTS_DISPLAY_MODE)
    )
del _valid_display_modes

_enable_404_suggestions_value = os.getenv('ENABLE_404_SUGGESTIONS')
if _enable_404_suggestions_value is None:
    ENABLE_404_SUGGESTIONS = False
else:
    ENABLE_404_SUGGESTIONS = _parse_bool_env(_enable_404_suggestions_value)
del _enable_404_suggestions_value

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'vdw_server.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
